name: adguardhome
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.68@sha256:09a24f05e110e53e213a340b22e5d3c8cdab12ff9be6775388c71b140255c54c
    container_name: adguardhome
    volumes:
      - ${DATA_DIR}/adguardhome/work:/opt/adguardhome/work
      - ${DATA_DIR}/adguardhome/conf:/opt/adguardhome/conf
    # dclint disable-line no-unbound-port-interfaces
    ports:
      - '${DNS_INTERFACE}:53:53/tcp'
      - '${DNS_INTERFACE}:53:53/udp'
    networks:
      - adguardhome-web
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.adguardhome.entrypoints: https
      traefik.http.routers.adguardhome.rule: Host(`adguard.${HOST}`)
      traefik.http.services.adguardhome.loadbalancer.server.port: 80
      traefik.tcp.routers.adguardhome-dns.entrypoints: dns
      traefik.tcp.routers.adguardhome-dns.rule: HostSNI(`adguard.${HOST}`)
      traefik.tcp.routers.adguardhome-dns.tls: true
      traefik.tcp.routers.adguardhome-dns.service: adguardhome-dns
      traefik.tcp.services.adguardhome-dns.loadbalancer.server.port: 53
      readme.description: Network-wide ads & trackers blocking DNS server.
      readme.links.docker: https://hub.docker.com/r/adguard/adguardhome
networks:
  adguardhome-web:
    name: adguardhome-web
